### ISSUE TITLE
Actiona page deoesnt work, dont know how to correctly download and compile Actiona

### ISSUE THREAD

**Issue by AdrienRH** [Jmgr/actiona#111]
Hi, i love your Actiona program, helping a lot but i accidently installed older version from web which dont have some important functions for me. I tried to find latest version but http://actiona.tools page is not working. 
Also tried Get & compile the latest version on win10 but it is too hard for me :(
Can u record tutorial how to do this https://wiki.actiona.tools/doku.php?id=en:compilation&#get_compile_the_latest_version it took me like 5 hours to install all those programs (40GB+) and i am just tired of trying to compile this :( There are folders and files missing, multiple folders that containing *.lib files in OpenCV, always building project in MVSC2019 not 2015.. etc... so many unknown errors. 
I just need back previous version :)

**Comment by Jmgr** [comment]
Hi. Sorry for that, the web site should work again now.

Windows compilation is often a pain, especially when using C++ and dependencies. In addition, Windows will not allow a program to manipulate the mouse cursor or simulate key pressed if the program is not digitally signed or you are starting it with admin rights. And installed in Program Files.

There is no precompiled version of Qt for MSVC 2019, so you can only use MSVC 2017. Sadly you also have to compile OpenCV yourself because they do not provide any precompiled version for this compiler either.

**Comment by AdrienRH** [comment]
Thanks, page working again :)
