### ISSUE TITLE
Is there planning for Macro Recorder?

### ISSUE THREAD

**Issue by Stamimail** [Jmgr/actiona#120]
Like in jitbit macro recorder.
To add a Record button, a command that will record the user actions and put them in the list.

**Comment by Jmgr** [comment]
This as been requested multiple times, actually. It is more complicated than it seems because Actiona is cross-platform, and Windows and Linux distributions have a completely different way of handling input. Key names and identifiers are completely different. Some keys are missing, some are only present on some keyboard layout. I do have a partial implementation of this, but it will require quite a bit of work to be released. It would be a great feature to have.

So to answer your question: yes, but not soon.
