### ISSUE TITLE
dark theme compatibility

### ISSUE THREAD

**Issue by sidmint** [Jmgr/actiona#128]
I use dark theme primarily all time [Mint19.3] but Actiona UI goes bad with it and is only usable with light theme. So compatibility wtih dark theme is requested.
Thank you for Actiona anyway.

**Comment by halfheart-games** [comment]
I was going to report the same thing. I found that windows with specifically coloured backgrounds are where the problem is. Because Actiona is, correctly, picking up the font colour as white, it renders on those light coloured backgrounds and is hard to read. I think if those windows using light purple, yellow, etc. backgrounds also forced a black font colour, everything would be fine.

As far as I know, this is only the 'edit action' window, but I'm new to the software and haven't used it much yet, so there may be other windows affected.

![2023 09 27_103331](https://github.com/Jmgr/actiona/assets/72930800/dc56941e-49ac-4063-bffd-9696b010d0ad)
![2023 09 27_103859](https://github.com/Jmgr/actiona/assets/72930800/aa36ef37-0e58-4092-9cab-7f3819dd2455)

**Comment by Jmgr** [comment]
I will add support for a dark theme, probably using https://github.com/ColinDuquesnoy/QDarkStyleSheet

**Comment by Jmgr** [comment]
Also the purple and yellow background on action parameters will be gone in the next version.

**Comment by Jmgr** [comment]
Implemented, will be added to the next version.
