### ISSUE TITLE
Pass parameter to procedure

### ISSUE THREAD

**Issue by Drigtime** [Jmgr/actiona#135]
Is it possible to pass parameters when calling a procedure ?
In the doc it says that it is not possible "Procedures doesn't have any parameters (yet)" but I was just wondering if it has been implemented and the doc didn't get updated

Very nice software btw

**Comment by prudowicz** [comment]
Yes, it is possible using a workaround. This is like, set your variable before procedure declaration (begin). Then use your variable in your procedure. Again, before calling your procedure just set same variable as you use in your procedure with value as you wish. I was wondering at gui-releted setting parameters, but this trick has filled my desires.

This is possible because all variables in your script are treated as in global scope.
