### ISSUE TITLE
[Suggestion] Add New Feature

### ISSUE THREAD

**Issue by softplace-io** [Jmgr/actiona#195]
There is a program called **Tinytask**.
This program reproduces what was done on the mouse and keyboard.
It would be interesting to have something like this in the Action.

Thanks !

**Comment by Jmgr** [comment]
Thanks for the suggestion. This is something that I have worked on in the past but has multiple challenges. The biggest one being keeping the compatibility of recorded actions across operating systems.

When clicks and key presses are recorded the operating system provides IDs that will ensure you get the same effect if you replay the events. Those IDs are specific to an operating system, and sometimes even specific to a hardware configuration. Either you record those and won't be able to replay on another operating system, or you ignore them and replaying doesn't work very well everywhere... That is the bane of writing a cross platform automation tool I'm afraid.

Closing because it is not something that can be done at the moment, unfortunately.
