### ISSUE TITLE
Git versión no compile in Gentoo 

### ISSUE THREAD

**Issue by dvastazion** [Jmgr/actiona#34]
main.cpp:105:10: error: #error ("You need Qt 5.2.0 or later to compile Actiona Executer");
         #error("You need Qt 5.2.0 or later to compile Actiona Executer");
          ^
Makefile:254: recipe for target 'generated/main.o' failed
make[1]: *** [generated/main.o] Error 1
make[1]: Leaving directory '/opt/actionaz/actexecuter'
Makefile:156: recipe for target 'sub-actexecuter-make_default-ordered' failed
make: *** [sub-actexecuter-make_default-ordered] Error 2

...but qt5 is not in the requeriments...

**Comment by Jmgr** [comment]
That's because the master branch contains the latest updates, not only bug fixes. You could use the v3.8.0 tag to select an older commit where the code was still using Qt 4.
The next version of Actiona (3.9.0, not published yet) will be using Qt 5. I will update the documentation when it will be out.

**Comment by dvastazion** [comment]
Thanks ;)
