### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by zvodd** [Jmgr/actiona#35]
Could we possibly get a some instructions for setting up a windows build environment?
Can I cross-compile Actiona in Linux for windows? Or do we need to setup windows environment?

**Comment by zvodd** [comment]
So I tried compiling on a clean install of Ubuntu 12.04.5 (after running "apt-get update & apt-get upgrade")
I followed [These Instructions](https://wiki.actiona.tools/doku.php?id=en:compilation) from the wiki.

> vagrant@precise32:/vagrant/actiona-master$ qmake -r && make
> Reading /vagrant/actiona-master/tools/tools.pro
> Reading /vagrant/actiona-master/actiontools/actiontools.pro
> Reading /vagrant/actiona-master/executer/executer.pro
> Reading /vagrant/actiona-master/actexecuter/actexecuter.pro
> Reading /vagrant/actiona-master/gui/gui.pro
> Reading /vagrant/actiona-master/actions/actionpackinternal/actionpackinternal.pro
> Reading /vagrant/actiona-master/actions/actionpackwindows/actionpackwindows.pro
> Reading /vagrant/actiona-master/actions/actionpackdevice/actionpackdevice.pro
> Reading /vagrant/actiona-master/actions/actionpacksystem/actionpacksystem.pro
> /vagrant/actiona-master/actions/actionpacksystem/systeminfo/systeminfo.pri:85: Unknown test function: qtHaveModule
> Reading /vagrant/actiona-master/actions/actionpackdata/actionpackdata.pro
> cd tools/ && make -f Makefile
> make[1]: Entering directory `/vagrant/actiona-master/tools'
> g++ -c -pipe -std=c++11 -O2 -O3 -s -Wall -W -D_REENTRANT -fPIC -DQT_WEBKIT -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DACT_VERSION=3.8.0 -DACT_SCRIPT_VERSION=1.1.0 -DACT_BUILD_NAME=\"\" -DACT_PREFIX="\"/usr/local\"" -DACT_LIBDIR="\"lib\"" -DTOOLS_LIBRARY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Igenerated -o generated/version.o version.cpp
> cc1plus: error: unrecognized command line option '-std=c++11'
> make[1]: *** [generated/version.o] Error 1
> make[1]: Leaving directory `/vagrant/actiona-master/tools'
> make: *** [sub-tools-make_default-ordered] Error 2

**Comment by Jmgr** [comment]
> Could we possibly get a some instructions for setting up a windows build environment?
Since Actiona 3.9.0 and the move from Qt 4 to Qt 5, the Windows build procedure has been simplified, so when the 3.9.0 version will be released I will also update the wiki accordingly.
Building version 3.8.0 or earlier versions on Windows was a bit more complicated and I never got the time or motivation to write a guide to do it. Sorry about that.

> Can I cross-compile Actiona in Linux for windows? Or do we need to setup windows environment?
GCC is not an "officially" supported compiler on Windows, mainly because the use of some system APIs that are not available when using MinGW (for example). So, cross-compilation is probably not possible, since you will have to use MSVC to build binaries for Windows.

> So I tried compiling on a clean install of Ubuntu 12.04.5 (after running "apt-get update & apt-get upgrade")
> I followed These Instructions from the wiki.
You also need GCC 4.7 to build Actiona. I will add this to the wiki right now.
You could install a more recent version of Ubuntu, or try this: http://askubuntu.com/questions/113291/how-do-i-install-gcc-4-7

**Comment by sakazuki** [comment]
Hello Jmgr,
Thank you for your great work.

I want to build Actiona on Windows.
Cloud you let me know the windows build procedure ?

**Comment by Jmgr** [comment]
Hi,
I have updated the wiki page: https://wiki.actiona.tools/doku.php?id=en:compilation&#windows

**Comment by sakazuki** [comment]
I could build it on windows by your procedure.

Regards,

**Comment by Jmgr** [comment]
Great. Thanks for the feedback.
