### ISSUE TITLE
Drop bundled libqxt?

### ISSUE THREAD

**Issue by cicku** [Jmgr/actiona#39]
Hi,

I've been working on packaging this into Fedora for more than a year. I found that libqxt has been bundled into sources. Since libqxt has been packaged by many distros, is it OK to ge rid of these in sources?

Thanks.

**Comment by Jmgr** [comment]
This is sadly not possible for a number of reasons:
* libqxt has never been ported to Qt5 "officially"
* consequently, the packaged libqxt (as far as I know) are not compatible with Qt5
* libqxt is not maintained anymore, which implies that it will probably removed from most distros in the future
* the authors themselves advised on copying the parts of libqxt we are interested in instead of using it as a library because it was not maintained anymore (however, the page where this was written doesn't seem to exist anymore)

**Comment by cicku** [comment]
Understood. Thanks.
