### ISSUE TITLE
Actiona/Ubuntu 17.10

### ISSUE THREAD

**Issue by RPassanha** [Jmgr/actiona#67]
I have been a problem to use the action and Ubuntu 17.10, many actions don't work properly such as "Find Image" and " Move cursor". Can you help me?
Thanks!

**Comment by Jmgr** [comment]
That is because of Wayland. In Ubuntu 17.10 they decided to use it by default. The problem is that Wayland doesn't allow applications to send or record input like mouse clicks or key presses to/from other applications. Actiona will never work with Wayland until they do something about this.

A workaround is to use Xorg instead of Wayland: https://itsfoss.com/switch-xorg-wayland/

**Comment by Jmgr** [comment]
I have also added a warning in the future version 3.9.3 and created a page on the wiki explaining the issue: https://wiki.actiona.tools/doku.php?id=en:x11notdetected

**Comment by RPassanha** [comment]
Thanks for you help!
