### ISSUE TITLE
Dialog box without button (or disabled button)

### ISSUE THREAD

**Issue by Matioupi** [Jmgr/actiona#89]
Hello, thanks for this great piece of software !

Is it possible to display a dialog box without "Ok" or "Yes / No" button (or with a disabled "Ok" Button ?

**Comment by Jmgr** [comment]
Hi, yes, but you will have to write some Javascript code within a Code action.
For instance:
```javascript
var messagebox = new MessageBox({
	title: "Some title",
	text: "Some text",
	buttons: MessageBox.NoButton
});
messagebox.show();
```
Note that this will not be blocking for your script, so you will have to have another action later that blocks the script execution (for instance a Key condition). You can also replace show() by showModal(), but since no buttons are shown there will be not easy way to close the dialog.
