### ISSUE TITLE
How to run actexec headless!?

### ISSUE THREAD

**Issue by chyapura** [Jmgr/actiona#98]
I have a Raspberry Pi 3 (with Raspbian Stretch) and I mounted a webserber. I have Actiona installated too.
I can program two o three .ascr script (to open some apps, write data in some files and save it), and I can execute them from Actiona IDE, from a bash console (using actexec command), and from a Phyton script (IDLE3) using subprocess.Popen() function.
But I need execute the .ascr scripts remotely from a user frendly web page (with forms, buttons, etc. usin HTML, PHP and MySQL). For this, I use CGI scripts writed in Python.
But when I try execute the actexec command, I have got an error:
QXcbConnection: Could not connect to display 
Aborted 
Please, how could I to fix this problem?
Thanks

**Comment by Jmgr** [comment]
Hi, sorry for the late answer!

The issue here is that ActExec doesn't know which X display to use. You can create an environment variable named DISPLAY just before calling ActExec, and setting it to the address of the X display. On a typical Linux desktop it is often ":0" or ":1".

While connected to your Raspberry through SSH you can try opening a program with a graphical interface, for example xeyes. It should output a similar error. Then try prefixing the display number:
`DISPLAY=:0 xeyes`
This should display two eyes on the screen. Then you just have to do the same when calling ActExec.
